vich_uploader:
    db_driver: orm

    mappings:
       espece_image:
           uri_prefix: /assets/images/especes
           upload_destination: '%kernel.project_dir%/public/assets/images/especes'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true

       site_image:
           uri_prefix: /assets/images/sites
           upload_destination: '%kernel.project_dir%/public/assets/images/sites'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
