<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLhOXYby\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLhOXYby/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLhOXYby.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLhOXYby\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLhOXYby\App_KernelDevDebugContainer([
    'container.build_hash' => 'LhOXYby',
    'container.build_id' => 'ae07c1c8',
    'container.build_time' => 1611007585,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLhOXYby');
